### ISSUE TITLE
想知道一下你是有参考资料么

### ISSUE THREAD

**Issue by yourgentlesmile** [liuchuo/Java-exercise#1]
想知道一下，你是有参考资料么，对于这个项目

**Comment by liuchuo** [comment]
什么参考资料。。自己写的课程设计。。

**Comment by yourgentlesmile** [comment]
我知道是你的课程设计呀，就是像spring security的运用，你不会整个他的验证体系都记下来了吧，总有参考资料嘛，我是这个意思(￣▽￣)／

**Comment by liuchuo** [comment]
说实话还真的记在了脑子里……哈哈哈哈哈～ 之前有看过《Spring实战》那本书，就是封面上面有个奇怪的人站在那里的那本～

**Comment by yourgentlesmile** [comment]
嗯呢知道啦~7 hours ago .....修仙哟 (｀・ω・´)
